export const actionTypes = {
  FETCH_HEADER: "FETCH_HEADER",
  FETCH_FOOTER: "FETCH_FOOTER",
  FETCH_ABOUT: "FETCH_ABOUT",
  FETCH_MAINSLIDER: "FETCH_MAINSLIDER",
  FETCH_PRODUCTSLIDER: "FETCH_PRODUCTSLIDER",
  FETCH_TEAM: "FETCH_TEAM",
  FETCH_YOUTUBE: "FETCH_YOUTUBE",
};
