export const actionTypes = {
  // FETCH_HEADER: "FETCH_HEADER",
  FETCH_HEADER_REQUEST: "FETCH_HEADER_REQUEST",
  FETCH_HEADER_SUCCESS: "FETCH_HEADER_SUCCESS",
  FETCH_HEADER_FAILURE: "FETCH_HEADER_FAILURE",

  // FETCH_FOOTER: "FETCH_FOOTER",
  FETCH_FOOTER_REQUEST: "FETCH_FOOTER_REQUEST",
  FETCH_FOOTER_SUCCESS: "FETCH_FOOTER_SUCCESS",
  FETCH_FOOTER_FAILURE: "FETCH_FOOTER_FAILURE",

  // FETCH_ABOUT: "FETCH_ABOUT",
  FETCH_ABOUT_REQUEST: "FETCH_ABOUT_REQUEST",
  FETCH_ABOUT_SUCCESS: "FETCH_ABOUT_SUCCESS",
  FETCH_ABOUT_FAILURE: "FETCH_ABOUT_FAILURE",

  // FETCH_MAINSLIDER: "FETCH_MAINSLIDER",
  FETCH_MAINSLIDER_REQUEST: "FETCH_MAINSLIDER_REQUEST",
  FETCH_MAINSLIDER_SUCCESS: "FETCH_MAINSLIDER_SUCCESS",
  FETCH_MAINSLIDER_FAILURE: "FETCH_MAINSLIDER_FAILURE",

  // FETCH_PRODUCTSLIDER: "FETCH_PRODUCTSLIDER",
  FETCH_PRODUCTSLIDER_REQUEST: "FETCH_PRODUCTSLIDER_REQUEST",
  FETCH_PRODUCTSLIDER_SUCCESS: "FETCH_PRODUCTSLIDER_SUCCESS",
  FETCH_PRODUCTSLIDER_FAILURE: "FETCH_PRODUCTSLIDER_FAILURE",

  // FETCH_TEAM: "FETCH_TEAM",
  FETCH_TEAM_REQUEST: "FETCH_TEAM_REQUEST",
  FETCH_TEAM_SUCCESS: "FETCH_TEAM_SUCCESS",
  FETCH_TEAM_FAILURE: "FETCH_TEAM_FAILURE",

  // FETCH_YOUTUBE: "FETCH_YOUTUBE",
  FETCH_YOUTUBE_REQUEST: "FETCH_YOUTUBE_REQUEST",
  FETCH_YOUTUBE_SUCCESS: "FETCH_YOUTUBE_SUCCESS",
  FETCH_YOUTUBE_FAILURE: "FETCH_YOUTUBE_FAILURE",

  CHANGE_NAV_BG: "CHANGE_NAV_BG",
  // OPEN_VIDEO: "OPEN_VIDEO",
  // CLOSE_VIDEO: "CLOSE_VIDEO",
  OPEN_SLIDE_MENU: "OPEN_SLIDE_MENU",
  CLOSE_SLIDE_MENU: "CLOSE_SLIDE_MENU",

  FETCH_FILTERS: "FETCH_FILTERS",

  // FETCH_PRODUCT_LIST: "FETCH_PRODUCT_LIST",
  FETCH_PRODUCTLIST_REQUEST: "FETCH_PRODUCTLIST_REQUEST",
  FETCH_PRODUCTLIST_SUCCESS: "FETCH_PRODUCTLIST_SUCCESS",
  FETCH_PRODUCTLIST_FAILURE: "FETCH_PRODUCTLIST_FAILURE",

  SEND_FILTERS: "SEND_FILTERS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ALL: "CLEAR_ALL",
  PLUS_QTY: "PLUS_QTY",
  MINUS_QTY: "MINUS_QTY",
  FETCH_PRODUCT_DETAIL: "FETCH_PRODUCT_DETAIL",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
};
