export const actionTypes = {
  FETCH_HEADER: "FETCH_HEADER",
  FETCH_FOOTER: "FETCH_FOOTER",
  FETCH_ABOUT: "FETCH_ABOUT",
  FETCH_MAINSLIDER: "FETCH_MAINSLIDER",
  FETCH_PRODUCTSLIDER: "FETCH_PRODUCTSLIDER",
  FETCH_TEAM: "FETCH_TEAM",
  FETCH_YOUTUBE: "FETCH_YOUTUBE",
  CHANGE_NAV_BG: "CHANGE_NAV_BG",
  OPEN_VIDEO: "OPEN_VIDEO",
  CLOSE_VIDEO: "CLOSE_VIDEO",
};
